version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: red_social
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - red_social_network

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - red_social_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - db
    networks:
      - red_social_network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jonhdoe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: StrongPassword
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - red_social_network 
    # Servicio para Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuraci√≥n de Prometheus
      - prometheus_data:/prometheus  # Volumen para almacenar datos
    ports:
      - "9090:9090"  # Puerto para acceder a la interfaz web de Prometheus
    restart: unless-stopped
    networks:
      - red_social_network

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@db:5432/red_social?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - red_social_network

volumes:
  postgres_data:
  grafana_data:
  pgadmin-data:
  prometheus_data:


networks:
  red_social_network:
    driver: bridge
